const exclamations = [
    "Oh boy",
    "Hooray",
    "Whoopee",
    "Hot dog",
    "Yippee",
    "Wow",
    "Great",
    "Wonderful",
    "Goody",
    "Hurrah",
    "Gee whiz",
    "Oh joy",
    "Yea",
    "Oh my",
    "Golly",
    "Goody-goody",
    "Hot damn",
    "Oh goody",
    "Hoorah",
    "Eureka",
    "Oh gee",
    "Yahoo",
    "Happy day",
    "All right",
    "Fantastic",
    "Gosh",
    "Horray",
    "Hot diggety",
    "How wonderful",
    "My goodness",
    "Three cheers",
    "Ain't that something",
    "Beautiful",
    "Excellent",
    "Hey",
    "Hip-hip-hooray",
    "Hoo-wee",
    "Hot ziggety",
    "How about that",
    "Joy",
    "Oh great",
    "Oh that's great",
    "Oh wow",
    "Ooh goody",
    "Out of sight",
    "Bingo",
    "Bless the lord",
    "Boy oh beans",
    "Boy oh boy",
    "By golly",
    "Crazy",
    "Eldorado",
    "Far out",
    "Gee gosh darn",
    "Gee, that's wonderful",
    "Geeee-haww",
    "Golly buster",
    "Golly darn",
    "Good golly",
    "Good shot",
    "Goody gumdrop",
    "Goody-goody gumdrops",
    "Got some happy news",
    "Grand",
    "Happy days",
    "Hell's fire",
    "Hey, great",
    "Hip-hurrah, boys",
    "Hoo-hee",
    "Hooraw",
    "Hot diggety damn",
    "Hot diggety dog",
    "Hot dikkety",
    "How 'bout that",
    "How nice",
    "I don't believe it",
    "I'll be damned",
    "I'll be doggoned",
    "I'm glad of it",
    "Isn't that nice",
    "Isn't that something",
    "Jiminy crickets",
    "Joy, joy",
    "Jumping jelly-beans",
    "Look what we got",
    "Lovely",
    "My oh my",
    "Neat",
    "No foolin'",
    "Now you're talking",
    "Oh joy, oh boy, where do we go from here",
    "Oh look",
    "Oh yeah",
    "Ole",
    "Ooh-wee",
    "Peachy purple",
    "Raw",
    "Swell",
    "Terrific",
    "Thank you",
    "That sure was a humdinger",
    "This is great",
    "Tremendous",
    "Wahoo",
    "Well i'll be damned",
    "Whew",
    "Who'd have thought it",
    "Whoo boy",
    "Whoop",
    "Whoo-wee",
    "Woo",
    "Woo-ee",
    "Wow-ee",
    "Wowie",
    "Ya-ho",
    "Yea man",
    "Yeah",
    "Yeah man",
    "Yeee-ah",
    "Yes",
    "Yow",
    "Ziggety-damn"
];

const systemSounds = {
    Basso: "Basso",
    Blow: "Blow",
    Bottle: "Bottle",
    Frog: "Frog",
    Funk: "Funk",
    Glass: "Glass",
    Hero: "Hero",
    Morse: "Morse",
    Ping: "Ping",
    Pop: "Pop",
    Purr: "Purr",
    Sosumi: "Sosumi",
    Submarine: "Submarine",
    Tink: "Tink"
};

export {
    exclamations,
    systemSounds
}
